import argparse
import re
from pathlib import Path

import torch

from .model import GPT, GPTConfig


SENTENCE_END = re.compile(r"[.!?](?:[\"')\]]*)?(?:\s|$)")
SPEECH = re.compile(r'"([^"\n]+)"')
QUESTION_START = re.compile(
    r"^(?:what|why|when|where|who|how|can|could|would|will|is|are|am|do|does|did|"
    r"shall|should|may|might|have|has|had)\b",
    re.IGNORECASE,
)
CAPITALIZED_WORD = re.compile(r"\b[A-Z][a-z]{2,}\b")
COMMON_SENTENCE_WORDS = {
    "After",
    "An",
    "And",
    "But",
    "Dad",
    "Finally",
    "From",
    "He",
    "Her",
    "His",
    "I",
    "It",
    "It's",
    "Little",
    "Mom",
    "One",
    "Once",
    "She",
    "That",
    "The",
    "They",
    "This",
    "There",
    "Thank",
    "Then",
    "When",
    "Wow",
    "We",
    "Yes",
    "You",
}


def _story_context(story: str, anchor: str, block_size: int) -> str:
    """Keep the character introduction and the newest prose in the model context."""
    available = max(block_size - len(anchor.encode("utf-8")) - 1, 1)
    recent_story = story[len(anchor) :].lstrip() if story.startswith(anchor) else story
    tail_bytes = recent_story.encode("utf-8")[-available:]
    tail = tail_bytes.decode("utf-8", errors="ignore")
    return f"{anchor} {tail}"


def _complete_sentences(text: str, sentence_count: int) -> str:
    endings = list(SENTENCE_END.finditer(text))
    if len(endings) < sentence_count:
        return text[: endings[-1].end()].strip() if endings else text.strip()
    return text[: endings[sentence_count - 1].end()].strip()


def _keep_main_character_name(story: str, name: str) -> str:
    def replace_name(match: re.Match[str]) -> str:
        word = match.group(0)
        return word if word in COMMON_SENTENCE_WORDS or word == name else name

    return CAPITALIZED_WORD.sub(replace_name, story)


def _clean_punctuation(story: str, name: str) -> str:
    """Repair punctuation artifacts without rewriting the model's wording."""
    story = re.sub(r"[ \t]*,[ \t]*", ", ", story)
    story = re.sub(r",([.!?])", r"\1", story)
    story = re.sub(r"([.!?])\s*,", r"\1", story)
    story = re.sub(r",\s*,+", ",", story)

    def clean_speech(match: re.Match[str]) -> str:
        speech = match.group(1).strip()
        speech = re.sub(r"\s+", " ", speech)
        if re.match(rf"{re.escape(name)}\s+(?=\w)", speech, re.IGNORECASE):
            speech = re.sub(rf"^({re.escape(name)})(\s+)", r"\1, ", speech, flags=re.IGNORECASE)
        if QUESTION_START.match(speech):
            speech = re.sub(r"[.!?]+$", "", speech).rstrip() + "?"
        elif not re.search(r"[.!?]$", speech):
            speech += "."
        return f'"{speech}"'

    story = SPEECH.sub(clean_speech, story)
    return re.sub(r'\?"\.', '?"', story)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a complete story with N1 without asking for a prompt.")
    parser.add_argument("--checkpoint", type=Path, default=Path("checkpoints/n1.pt"))
    parser.add_argument("--sentences", type=int, default=16, help="Number of sentences to generate")
    parser.add_argument("--max-tokens", type=int, default=1200, help="Hard maximum number of generated bytes")
    parser.add_argument("--temperature", type=float, default=0.55)
    parser.add_argument("--name", default="Alex", help="Main character name used to keep the story consistent")
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()
    if args.sentences < 1 or args.max_tokens < 1:
        parser.error("--sentences and --max-tokens must be positive")
    if args.seed is not None:
        torch.manual_seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)
    if checkpoint.get("encoding") != "utf-8-bytes":
        raise ValueError("checkpoint was created by an older incompatible trainer; train a new checkpoint")

    model = GPT(GPTConfig(**checkpoint["config"])).to(device)
    model.load_state_dict(checkpoint["model"])
    model.eval()

    if not re.fullmatch(r"[A-Za-z][A-Za-z'-]*", args.name):
        parser.error("--name must contain only letters, apostrophes, or hyphens")

    anchor = f"Once upon a time, there was a child named {args.name}."
    story = anchor
    generated_tokens = 0
    while generated_tokens < args.max_tokens and len(list(SENTENCE_END.finditer(story))) < args.sentences:
        context = _story_context(story, anchor, model.config.block_size)
        context_tokens = torch.tensor([[token for token in context.encode("utf-8")]], device=device)
        remaining = args.max_tokens - generated_tokens
        generated = model.generate(
            context_tokens,
            min(remaining, model.config.block_size),
            args.temperature,
            repetition_penalty=1.08,
        )[0].tolist()
        continuation = bytes(generated[len(context_tokens[0]) :]).decode("utf-8", errors="replace")
        if not continuation:
            break
        story = f"{story.rstrip()} {continuation.lstrip()}"
        generated_tokens += len(continuation.encode("utf-8"))
        if len(continuation) < model.config.block_size:
            break

    story = _complete_sentences(story, args.sentences)
    story = _keep_main_character_name(story, args.name)
    story = _clean_punctuation(story, args.name)

    print(story)


if __name__ == "__main__":
    main()