import argparse
import re
from pathlib import Path

import torch

from .model import GPT, GPTConfig


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a complete story with N1 without asking for a prompt.")
    parser.add_argument("--checkpoint", type=Path, default=Path("checkpoints/n1.pt"))
    parser.add_argument("--sentences", type=int, default=8, help="Number of sentences to generate")
    parser.add_argument("--max-tokens", type=int, default=800, help="Hard maximum number of generated bytes")
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()
    if args.sentences < 1 or args.max_tokens < 1:
        parser.error("--sentences and --max-tokens must be positive")
    if args.seed is not None:
        torch.manual_seed(args.seed)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    checkpoint = torch.load(args.checkpoint, map_location=device, weights_only=False)
    if checkpoint.get("encoding") != "utf-8-bytes":
        raise ValueError("checkpoint was created by an older incompatible trainer; train a new checkpoint")

    model = GPT(GPTConfig(**checkpoint["config"])).to(device)
    model.load_state_dict(checkpoint["model"])
    model.eval()

    opening = "Once upon a time"
    prompt_tokens = torch.tensor([[token for token in opening.encode("utf-8")]], device=device)
    generated = model.generate(prompt_tokens, args.max_tokens, args.temperature)[0].tolist()
    story = bytes(generated).decode("utf-8", errors="replace")
    endings = list(re.finditer(r"[.!?](?:[\"')\]]*)?(?:\s|$)", story))
    if len(endings) >= args.sentences:
        story = story[: endings[args.sentences - 1].end()].strip()

    print(story)


if __name__ == "__main__":
    main()